### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by HmimH** [yogajones/ot-harjoitustyo#2]
12.12.2023 - 21.45

The idea is very solid and works well with the course. I found no obvious bugs using it.

As a whole your code is very good and I am unable to find much to criticise. Your documentation is mostly in order and in the places it isn't you've generally noted that the information is under construction. The ui is neatly organised. The general structures of the entities are also in order. Most functions have been docstringed, and while not all have been, as you have noted this too is a work in progress. Your test coverage is high and all tests so far are passing.

If you wanted to look at something to improve you might want to consider the ease of usage - for example giving the current name of the objective when renaming it and allowing for the use of 'enter' in entering the objectives. But obviously these are minor suggestions and there are many technical improvements you are planning on first.

Very good work overall. :)

**Comment by yogajones** [comment]
Many thanks for your review! Your great suggestion to improve the user experience with a pre-filled field for renaming objectives has been taken into account, thank you.
